Refactor Dictionary
* Moved Dictionary stuff into util/dictionary and namespace rhdl::dictionary
* Splitted Dictionary functionality in two: Lookup and order, both individually
  configurable via objects in dictionary::order: Unordered, Lexical and FCFS,
  the latter only being usable as order.
  Unordered (via hash) lookup does not work, since, apparently the transparency
  of hash and equality functors does not seem to be recognized

(gcc: /usr/include/c++/13/bits/stl_function.h:1430:11: error: no type named ‘type’ in ‘struct std::__has_is_transparent<rhdl::dictionary::order::Unordered::Hash<rhdl::dictionary::detail::LookupElement<const rhdl::CObject*, rhdl::dictionary::Order<std::set<const rhdl::CObject*, rhdl::dictionary::order::Lexical::Less<const rhdl::CObject*>, std::allocator<const rhdl::CObject*> > > > >, std::__cxx11::basic_string<char>, void>’)

BUGFIX: dictionareimpl(base)